version: '3.3'

services:
        django:
                image: sluggo-api:latest
                restart: unless-stopped
                ports:
                        - "8000:8000"
                env_file: ./.env
                volumes:
                        - static_volume:/usr/share/nginx/html/
        nginx:
                image: sluggo-spa:latest
                restart: unless-stopped
                volumes:
                        - ./confs/nginx.conf:/etc/nginx/nginx.conf:ro
                        - static_volume:/usr/share/nginx/html/
                        - ./data/certbot/www:/var/www/certbot
                        - ./data/certbot/conf:/etc/letsencrypt
                ports:
                        - "80:80"
                        - "443:443"
                depends_on:
                        - django
                command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        certbot:
                image: certbot/certbot
                restart: unless-stopped
                volumes:
                        - ./data/certbot/www:/var/www/certbot
                        - ./data/certbot/conf:/etc/letsencrypt
                entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
        static_volume:
