name: Sluggo API CI

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout Sluggo-API
      uses: actions/checkout@v3
      with:
        repository: Sluggo-Issue-Tracker/Sluggo-API
        path: ./Sluggo-API
        # using the current branch
    - name: Checkout Sluggo-SPA
      uses: actions/checkout@v3
      with:
        repository: Sluggo-Issue-Tracer/Sluggo-SPA
        path: ./Sluggo-SPA
        ref: develop # will need to change later, deployed env only develop
    - name: Checkout Sluggo
      uses: actions/checkout@v3
      with:
        repository: Sluggo-Issue-Tracker/Sluggo
        path: ./Sluggo
        ref: main
    - name: Build the Img for API
      run: >
        docker build ./Sluggo-API --file ./Sluggo-API/Dockerfile
        --tag sluggo-api:$(date +%s) --tag sluggo-api:develop
    - name: Build the Img for SPA
      run: >
        docker build ./Sluggo-SPA --file ./Sluggo-SPA/Dockerfile
        --tag sluggo-spa:$(date +%s) --tag sluggo-spa:develop
    - name: Save both imgs to directory
      run: |
        mkdir ./imgs
        docker save sluggo-api:develop | gzip ./imgs/sluggo-api.tar.gz
        docker save sluggo-spa:develop | gzip ./imgs/sluggo-spa.tar.gz
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'placeholder'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Upload images and Sluggo files with rsync
      run: |
        rsync -avz ./imgs ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/imgs
        rsync -avz ./Sluggo ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/Sluggo
    - name: Run the software!
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        script: |
          docker load < ~/imgs/sluggo-api.tar.gz
          docker load < ~/imgs/sluggo-spa.tar.gz
          cd ~/Sluggo
          docker-compose up -d
