name: Sluggo CI

on:
  # configure manual parameters
  workflow_dispatch:
    inputs:
      api_ref:
        description: 'branch or commit sha of Sluggo-API to run against'
        type: string
        required: true
        default: 'develop'
      spa_ref:
        description: 'branch or commit sha of Sluggo-SPA to run against'
        type: string
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout Sluggo-API
      uses: actions/checkout@v3
      with:
        repository: Sluggo-Issue-Tracker/Sluggo-API
        path: ./Sluggo-API
        ref: ${{ inputs.api_ref }}
        # using the current branch
    - name: Checkout Sluggo-SPA
      uses: actions/checkout@v3
      with:
        repository: Sluggo-Issue-Tracker/Sluggo-SPA
        path: ./Sluggo-SPA
        ref: ${{ inputs.spa_ref }}
    - name: Checkout Sluggo
      uses: actions/checkout@v3
      with:
        repository: Sluggo-Issue-Tracker/Sluggo
        path: ./Sluggo
        ref: ${{ github.branch }}
    - name: Build the Img for API
      run: >
        docker build ./Sluggo-API --file ./Sluggo-API/Dockerfile
        --tag sluggo-api
    - name: Copy env file to SPA dir
      run : echo "${{ secrets.SPA_ENV }}" > ./Sluggo-SPA/.env
    - name: Build the Img for SPA
      run: >
        docker build ./Sluggo-SPA --file ./Sluggo-SPA/Dockerfile
        --tag sluggo-spa
    - name: Save both imgs to directory
      run: |
        mkdir ./imgs
        docker save sluggo-api | gzip > ./imgs/sluggo-api.tar.gz
        docker save sluggo-spa | gzip > ./imgs/sluggo-spa.tar.gz
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'placeholder'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Copy env file to Sluggo dir
      run : echo "${{ secrets.API_ENV }}" > ./Sluggo/.env
    - name: Upload images and Sluggo files with rsync
      run: |
        rsync -avz ./imgs ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/
        rsync -avz ./Sluggo ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/
    - name: Run the software!
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker load < ~/imgs/sluggo-api.tar.gz
          docker load < ~/imgs/sluggo-spa.tar.gz
          cd ~/Sluggo
          ./init-letsencrypt.sh
          export NGINX_HOST=${{ secrets.NGINX_HOST }}
          envsubst '${NGINX_HOST}'' < ./confs/nginx.template > ./confs/nginx.conf
          docker-compose down -v
          docker-compose up -d
